{% set version = "0.3.1" %}

package:
  name: crayons
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/crayons/crayons-{{ version }}.tar.gz
  sha256: dcb85b87aa03bb65bd3a073d012796b024cabeb086033e616759e2abb769440b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - colorama

test:
  imports:
    - crayons


about:
  home: https://github.com/MasterOdin/crayons
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: TextUI colors for Python

extra:
  recipe-maintainers:
    - ocefpaf
